Learning-Fuze/c219_sportsstats

src/components/app.js
src/components/browse_sports/browse_sports.scss
src/components/browse_sports/index.js

Includes instructional text
Still needs routing functionality

Created list of sports

---

src/components/browse_overwatch/index.js
src/components/browse_overwatch/ow_team.js
src/components/browse_overwatch/ow_team_list.js
src/components/browse_teams/index.js
src/components/home_team_list/index.js
src/components/home_team_list/team_button/team_button.js
src/components/home_team_list/team_button/team_button.scss

set up dynamic routing for nba teams
added 'quicksand' font

created overwatch team page, ready for dummy data to display

---

public/api/data/getgamestats.json
public/api/data/getteam.json
src/components/stats/index.js
src/components/stats/players_stats/players_stats.js
src/components/stats/players_stats/players_stats.scss

tables now render based on state

---

src/components/browse_teams/browse.scss
src/components/browse_teams/confirm_buttons.js
src/components/browse_teams/index.js
src/components/browse_teams/team.js
src/components/browse_teams/team_list.js

console logs click handlers, have not set up the route to go to specific page yet

added confirm and back to sports buttons when selecting NBA team

---

public/api/getgameid.php
public/api/getgamestats.php

output matches dummy data, except home/away instead of team1/team2, and team abbreviation instead of full name

Completed endpoint for MySportsFeeds API call

---

src/components/app.js
src/components/log_in/package.json
src/components/sign_up/index.js
src/components/sign_up/sign_up_form.js

Username, password, and confirm password fields
Submit button (not functional yet)
Added link to sign up page on log in page

Created basic sign up page

---

src/assets/css/app.scss
src/components/app.js
src/components/home_team_list/team_button/team_button.js
src/components/log_in/log_in_form.js
src/components/nav/index.js
src/components/nav/nav.scss
src/components/nav/nav_footer.js
src/components/stats/index.js
src/components/stats/players_stats/players_stats.js
src/components/stats/players_stats/players_stats.scss
src/components/stats/team_score/team_score.js
src/components/stats/team_score/team_score.scss
src/components/stats/teams_tab/teams_tab.js
src/components/stats/teams_tab/teams_tab.scss

changed styling for entire STATS page
player stats section scrolls
page dynamic between desktop and mobile

added routing to bottom nav / STATS page intermediate css complete

---

src/assets/css/app.scss
src/components/app.js
src/components/home_team_list/team_button/team_button.js
src/components/log_in/log_in_form.js
src/components/nav/index.js
src/components/nav/nav.scss
src/components/nav/nav_footer.js
src/components/stats/index.js
src/components/stats/players_stats/players_stats.js
src/components/stats/players_stats/players_stats.scss
src/components/stats/team_score/team_score.js
src/components/stats/team_score/team_score.scss
src/components/stats/teams_tab/teams_tab.js
src/components/stats/teams_tab/teams_tab.scss

Trying out new fonts. Experiment with whatever you'd like!

Changed Logo Header font

---

src/assets/css/_media_query_mixins.scss
src/components/home_team_list/team_button/team_button.scss
src/components/landing_page/index.js
src/components/landing_page/landing_page.scss

Created a Sass mixin file for easy media queries. Import it from src/assets/css. The breakpoints are the same as Materialize.
Adjusted css on landing page to make it responsive across all devices.

Homepage css

---

src/components/browse_teams/browse.scss
src/components/browse_teams/team.js
src/components/landing_page/index.js

changed landing page button colors

changed background color for team buttons

---

src/components/browse_teams/browse.scss
src/components/browse_teams/confirm_buttons.js
src/components/browse_teams/team.js
src/components/browse_teams/team_list.js
src/components/home_team_list/index.js
src/components/home_team_list/team_button/team_button.js

colors for each team button are dynamic based on team's logo
clicking on team from my-teams will take you to relevant game
no error handling or deletion yet

Can now add multiple nba teams to my-teams page

---

public/api/getnbagamestats.php
src/components/stats/index.js
src/components/stats/players_stats/players_stats.js
src/components/stats/players_stats/players_stats.scss
src/components/stats/team_score/team_score.js

Date displays at top of score
Current quarter & time remaining display at bottom of score (time isn't formatted yet)
Added player position
Updated ternary for BKN/OKC

Updates to NBA data

---

src/components/nav/sidenav.js

can be easily changed
fooling around with the transition times
change in the config constant within sidenav.js

added a few swipe gestures to sidenav

---

src/components/browse_sports/browse_sports.scss
src/components/browse_sports/home_choose_sports.js
src/components/browse_sports/index.js
src/components/home_team_list/team_button/team_button.js
src/components/nav/nav.scss

feel free to change as you'd like

small color changes. play around with whatever colors you want!

---

public/api/getnbagameid.php
public/api/getnbagamestats.php
src/components/stats/team_score/team_score.js

still need to check that it won't pull games that haven't started yet

Now pulling live stats!

---

package-lock.json
package.json
src/actions/index.js
src/actions/types.js
src/components/stats/index.js
src/index.js
src/reducers/index.js
src/reducers/loading_reducer.js
src/reducers/stats_reducer.js
src/reducers/user_reducer.js

game stats reducer created
installed thunk middleware
game-stats-page now displays loadigscreen while waiting for axios response then renders game stats

loading screen reducer created

---

public/api/getnbagamestats.php
src/components/stats/team_score/team_score.js

Date is correct regardless of timezone
Time remaining is properly formatted
Current quarter is properly formatted

Fixed date, time remaining, and quarter bugs

---

package-lock.json
src/actions/index.js
src/actions/types.js
src/components/app.js
src/components/browse_teams/team_list.js
src/components/nba_stats/index.js
src/reducers/index.js
src/reducers/team_list_reducer.js

loading-screen component now unmounts where it's being used and resets to default value allowing the component to be re-used without errors

added team list reducer

---

public/api/addteam.php
public/api/delete-user-team.php
public/api/gethomepageteams.php

updated endpoints to reflect user input

Basic backend CRUD functionality completed

---

src/actions/index.js
src/components/home_team_list/index.js
src/components/home_team_list/team_button/team_button.js
src/components/nhl_stats/game_score/game_score.js
src/components/nhl_stats/index.js

player-stats.js needs reformatting

Pulling and displaying dummy data for nhl game stats

---

src/components/browse_teams/team.js
src/components/nba_stats/players_stats/nba_players_stats.scss
src/components/nba_stats/players_stats/players_stats.js
src/components/nba_stats/teams_tab/teams_tab.scss
src/components/nhl_stats/players_stats/nhl_players_stats.scss
src/components/nhl_stats/players_stats/players_stats.js
src/components/nhl_stats/teams_tab/teams_tab.js

Need to make headers of each position category sticky when scrolling through list

nhl player stats formatted for initial css

---

src/components/landing_page/index.js
src/components/nav/index.js

Navbar still resets on page reaload

nav bar now changes on successful sign in

---

src/components/home_team_list/index.js
src/components/home_team_list/team_button/team_button.js
src/components/nba_stats/index.js

Fixed a bug where only logged in or guest user's game stats would load.
Both logged in and guest user's game stats now load correctly

Display game stats hotfix

---

public/api/addteam.php

verified query success through postman

updated addteams query to handle the addition of multiple teams

---

src/components/home_team_list/index.js

Deletions accurately update database

logged in user's team deletions connected to endpoint 

---

src/components/browse_teams/confirm_buttons.js
src/components/browse_teams/team_list.js
src/components/home_team_list/index.js

Connected endpoint for add teams

signed in users can now save teams to their My teams page

---

src/actions/index.js
src/components/account/sign_up/index.js

Upon sign-up user is successfully logged in

---

src/components/home_team_list/home_team_list.scss
src/components/home_team_list/index.js
src/components/home_team_list/team_button/team_button.js
src/components/nav/nav.scss

Swipe works in mobile view
When screen is changed to tablet/desktop view, delete button appears to the side of the team button
On component mount correct view is assigned and changes respectively

Fixed responsive swipe to work and display correctly

---

src/components/browse_teams/team_list.js
src/components/nav/nav_footer.js

There is still a bug for logged in users on refresh.
Will first render local storage teams

Updated links to correctly route guest or signed in user

---

src/components/browse_teams/browse.scss
src/components/browse_teams/team.js
src/components/nba_stats/players_stats/nba_players_stats.scss
src/components/nba_stats/teams_tab/teams_tab.js
src/components/nhl_stats/players_stats/nhl_players_stats.scss
src/components/nhl_stats/teams_tab/teams_tab.js

blue tint taken off when item is clicked

team buttons do not change size when changing screen width

---

src/components/my_team_lists/team_button/team_button.js
src/components/my_team_lists/user/index.js
src/components/nba_stats/index.js
src/components/nhl_stats/index.js

fixed swipe...again.
removed loadingreducer and state from grabbing nba and nhl stats pages

i hate this swipe button so much.

---

src/actions/index.js
src/actions/types.js
src/components/account/index.js
src/components/account/sign_in/index.js
src/components/account/sign_up/index.js
src/components/account/sign_up/sign_up_form.js
src/reducers/user_reducer.js

only routes to browse page if account is successfully created
error messages clear on unmount

Added error handling for signup page if username is taken

---

src/assets/css/app.scss
src/components/browse_teams/confirm_buttons.js
src/components/browse_teams/team_list.js
src/components/my_team_lists/team_button/team_button.js
src/components/my_team_lists/user/index.js
src/components/nba_stats/players_stats/nba_players_stats.scss
src/components/nba_stats/players_stats/players_stats.js
src/components/nhl_stats/players_stats/nhl_players_stats.scss
src/components/nhl_stats/players_stats/players_stats.js

nav footer display none when > 600px
player stats increased to 70vh when > 600px
made team-list pulse dynamic based on teams chosen

added media queries for footer nav and player stats container

---

src/components/account/sign_in/index.js
src/components/account/sign_in/sign_in_form.scss
src/components/account/sign_up/index.js
src/components/account/sign_up/sign_up.scss
src/components/account/sign_up/sign_up_form.js

added logo to sign in/sign up pages
removed margins on confirm password field

Minor CSS polishing

---

src/components/account/sign_in/sign_in_form.js
src/components/landing_page/index.js
src/components/landing_page/landing_page.scss
src/components/nav/index.js

it was off-center
removed X in upper right corner of sidenav

changed positioning of landing page guest button

---

src/components/nba_stats/teams_tab/teams_tab.js
src/components/nhl_stats/teams_tab/teams_tab.js
src/components/nhl_stats/teams_tab/teams_tab.scss

CSS Hotfix teams tab nhl are now the same as nba

---

src/actions/index.js
src/components/app.js
src/components/my_team_lists/team_button/team_button.js
src/hoc/auth.js
src/index.js

checkAuth was moved up from App's component did mount method to the index file that renders the entire App.
On sign in auth is set to true in local storage
On refresh local storage is being checked before the call is made to check for auth on the backend.
If for some reason local storage auth is set to true but the backend call returns auth as false, the user will be logged out

Refresh bug fixed

---

src/components/nba_stats/team_score/team_score.js
src/components/nhl_stats/game_score/game_score.js

Now displays 'Game Starting Soon' instead of FINAL, 0:00

Fixed bug for score display just before game starts

---

src/assets/css/app.scss
src/components/app.js
src/components/my_team_lists/empty_homepage.js
src/components/my_team_lists/my_team_lists.scss
src/components/nav/nav.scss
src/components/nav/nav_footer.js

Fixed bug where the component was able to scroll when it shouldn't have

Component is now contained and has the proper background color

---

src/components/browse_teams/browse.scss
src/components/browse_teams/index.js
src/components/landing_page/index.js
src/components/nav/index.js
src/components/nav/nav.scss
src/components/nba_stats/players_stats/nba_players_stats.scss
src/components/nhl_stats/players_stats/nhl_players_stats.scss
src/components/nhl_stats/players_stats/players_stats.js

removed thin divider lines in nhl player stats table

fixed background image bleeding issue onto teams stats page

---

src/components/browse_sports/browse_sports.scss
src/components/browse_teams/browse.scss
src/components/browse_teams/confirm_buttons.js
src/components/browse_teams/index.js
src/components/landing_page/landing_page.scss
src/components/nba_stats/index.js
src/components/nba_stats/players_stats/nba_players_stats.scss
src/components/nba_stats/team_score/team_score.js
src/components/nba_stats/team_score/team_score.scss
src/components/nhl_stats/game_score/team_score.scss

removed #teams-main div along with its height to fix loading screen issues between selecting team and displaying their stats

changed positioning and sizing of elements on landing page

---

public/api/getnbagamestats.php
public/api/getnhlgamestats.php

still checks current season if season is currently going

Updated php curl requests to check latest season instead of current
